-- MariaDB Dump - Generated by MariaDB 10.4.32
-- Host: localhost
-- Database: crud_db_1733437165
-- ------------------------------------------------------
-- Server Version: 10.4.32-MariaDB

-- Configuración inicial
SET @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT;
SET @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS;
SET @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION;
SET NAMES utf8mb4;

SET @OLD_TIME_ZONE = @@TIME_ZONE;
SET TIME_ZONE = '+00:00';

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS;
SET UNIQUE_CHECKS = 0;

SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;

SET @OLD_SQL_MODE = @@SQL_MODE;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

SET @OLD_SQL_NOTES = @@SQL_NOTES;
SET SQL_NOTES = 0;

-- ------------------------------------------------------
-- Estructura de la tabla `persona`
-- ------------------------------------------------------
DROP TABLE IF EXISTS `persona`;

CREATE TABLE `persona` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) DEFAULT NULL,
  `apellido` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB 
  AUTO_INCREMENT=12 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------
-- Datos de la tabla `persona`
-- ------------------------------------------------------
LOCK TABLES `persona` WRITE;

-- Deshabilitar índices para mejorar el rendimiento durante la inserción
ALTER TABLE `persona` DISABLE KEYS;

INSERT INTO `persona` (`id`, `nombre`, `apellido`) 
VALUES 
  (2, 'men', 'asdfasdf'),
  (10, 'dip', 'asdf'),
  (11, 'k', 'fgsdfgsdfg');

-- Habilitar índices después de la inserción
ALTER TABLE `persona` ENABLE KEYS;

UNLOCK TABLES;

-- Restaurar configuraciones originales
SET TIME_ZONE = @OLD_TIME_ZONE;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
SET CHARACTER_SET_CLIENT = @OLD_CHARACTER_SET_CLIENT;
SET CHARACTER_SET_RESULTS = @OLD_CHARACTER_SET_RESULTS;
SET COLLATION_CONNECTION = @OLD_COLLATION_CONNECTION;
SET SQL_NOTES = @OLD_SQL_NOTES;

-- Fin del dump
-- Dump generado el 2024-12-06 a las 23:51:34
