

CREATE DATABASE MILENADIEGO;
USE MILENADIEGO;

CREATE TABLE Libros (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Titulo VARCHAR(255) NOT NULL,
    Autor VARCHAR(255) NOT NULL,
    ISBN VARCHAR(20),
    Precio DECIMAL(10,2)
);
